//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İntProg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uyeler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Uyeler()
        {
            this.Siparisler = new HashSet<Siparisler>();
        }
    
        public int uyeId { get; set; }
        public string uyeAdi { get; set; }
        public string uyeSoyadi { get; set; }
        public string uyeKullaniciAdi { get; set; }
        public string uyeSifre { get; set; }
        public string uyeTel { get; set; }
        public string uyeMail { get; set; }
        public string uyeAdres { get; set; }
        public int uyeYetki { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Siparisler> Siparisler { get; set; }
    }
}
